Add atomic kickstart for docker image generation
CentOS/sig-cloud-instance-build pull request #117
Opened 2017-11-26 06:45 UTC by abn

This is an initial attempt at adding an atomic-container base docker image for CentOS. I am not a 100% sure if this is the first step to get this accepted as an official image, happy to receive feedback on how to proceed with this.

Original thread on centos-devel from @kbsingh is available [here](https://lists.centos.org/pipermail/centos-devel/2017-March/015748.html).

The repository where the original project is housed is at https://github.com/kbsingh/atomic-container. I have cleaned up the commits, fixed up the KS to work with the containerbuild.sh script and reduced the image size further. An example image is available on [Docker Hub](https://hub.docker.com/r/alectolytic/centos-atomic/).

The packages have been updated to match what is provided with the [rhel-atomic image](https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/rhel-atomic).

2017-11-27 21:40 UTC, kbsingh commented on centos-atomic-7.ks
> +repo --name="microdnf" --baseurl="https://buildlogs.centos.org/cah-0.0.1" --cost=100
we dont want to use a buildlogs repo in the official builds, is there another source for this content ?

2017-11-27 21:42 UTC, kbsingh requested changes
can we find a non testing/buildlog source for the micro-dnf stack ?

2017-11-28 23:35 UTC, abn commented
@kbsingh the only place I can see this is at https://buildlogs.centos.org/centos/7/atomic/x86_64/Packages/ Not sure how where else to get it from or add to.

2025-01-05 01:21 UTC, abn commented
Closing this as this is clearly out of date. :)

2025-01-05 01:21 UTC, closed without merging